apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
  labels:
    app: example-cronjob
spec:
  # Run every 5 minutes
  schedule: "*/5 * * * *"

  # Do not allow overlapping runs
  concurrencyPolicy: Forbid
  # concurrencyPolicy: Allow | Forbid | Replace

  # If the job is missed by more than this, skip it
  startingDeadlineSeconds: 300

  # Retain limited Job history
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 300
      ttlSecondsAfterFinished: 1800

      template:
        metadata:
          labels:
            app: example-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cronjob-container
              image: busybox:1.36
              imagePullPolicy: IfNotPresent
              command:
                - sh
                - -c
                - |
                  echo "CronJob run at $(date)"
                  sleep 10
                  echo "CronJob finished"

              resources:
                requests:
                  cpu: "100m"
                  memory: "64Mi"
                limits:
                  cpu: "300m"
                  memory: "128Mi"