apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-metrics
  labels:
    app: node-metrics
spec:
  selector:
    matchLabels:
      app: node-metrics
  template:
    metadata:
      labels:
        app: node-metrics
    spec:
      hostNetwork: true     # so we can see host IP
      containers:
      - name: metrics
        image: alpine:3.18
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache procps coreutils &&
            while true; do
              echo "==== Node Metrics ===="
              echo "Node: $(hostname) IP: $(hostname -i)"
              echo "==== CPU Load ===="
              echo "$(cat /proc/loadavg)"
              echo "==== Memory: ===="
              echo "$(free -h)"
              echo "==== Disk ===="
              echo "$(df -h / | tail -1)"
              echo "---------------------"
              sleep 20
            done
        volumeMounts:
        - name: host-proc
          mountPath: /proc
          readOnly: true
        - name: host-root
          mountPath: /host
          readOnly: true
      volumes:
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-root
        hostPath:
          path: /
