apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-info
  labels:
    app: node-info
spec:
  selector:
    matchLabels:
      app: node-info
  template:
    metadata:
      labels:
        app: node-info
    spec:
      containers:
      - name: node-info
        image: alpine:3.18
        command: ["/bin/sh", "-c"]
        args:
          - >
            apk add --no-cache procps coreutils &&
            while true; do
              echo "Node: $(hostname -i)" > /tmp/index.html;
              echo "CPU Load: $(cat /proc/loadavg)" >> /tmp/index.html;
              echo "Memory: $(free -h | grep Mem)" >> /tmp/index.html;
              echo "Disk: $(df -h / | tail -1)" >> /tmp/index.html;
              sleep 5;
            done
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-info-ingress
spec:
  rules:
  - host: node1.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-info-node1
            port:
              number: 80
  - host: node2.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-info-node2
            port:
              number: 80
