apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
  labels:
    app: example-job
spec:
  # How many successful Pods are required
  completions: 1

  # How many Pods can run at the same time
  parallelism: 1

  # Number of retries before marking the Job as failed
  backoffLimit: 3

  # Hard timeout for the entire Job (seconds)
  activeDeadlineSeconds: 600

  # Automatically clean up Job + Pods after completion
  ttlSecondsAfterFinished: 3600

  template:
    metadata:
      labels:
        app: example-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job-container
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo "Job started at $(date)"
              sleep 5
              echo "Job completed successfully"

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"